To do list
Theophileaseh/To-Do-List-Webpack pull request #1
Opened 2022-03-23 17:21 UTC by Theophileaseh

Create and install
- webpack
- index.html file
- style.css file
- index.js file

2022-03-23 18:38 UTC, rotimiazeez reviewed
# Hi @Theophileaseh, 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have node modules ignored, making it nearly impossible to review your changes. Kindly make sure node modules is ignored and submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-03-24 07:10 UTC, FrederickMih reviewed
Hi @Theophileaseh , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project without linters configurations, node_modules folder not properly ignored(This makes your project impossible to review), your project is not working properly(index.js file is almost empty), your README file is almost empty. Please let's make sure that our project is working before submitting it for review. Reach out to me(@Fred) on slack if you still face any issues 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-24 09:40 UTC, rloterh commented
Hi Nwachan, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have an appropriate ReadMe.
Kindly note that _ReadMe_ is mostly the first place that visitors of this project's repository will go and therefore it has to be very detailed and professional. Also, it needs to be done well with respect to this capstone project,  which will likely feature on your portfolio. Therefore, kindly ensure to improve upon these aspects of your ReadMe:
- [ ] _Project description_, _how to set up_, _run and test this project_ **should be detailed, clear, and well** organized.
- [ ] OPTIONAL
The _code_ aspects in each procedure can be quoted with **backticks** to make the code description look cleaner.
- [ ] Include necessary screenshots, project demo links where applicable so as to give a birds-eye view of your project
- [ ] OPTIONAL
Kindly ensure that your ReadMe is _typo-free_. You can crosscheck by installing the [Grammarly plugin](https://www.grammarly.com/)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-24 11:45 UTC, omar-labana requested changes
Hi @Theophileaseh, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 11:45 UTC, omar-labana commented on src/index.html
> +            </div>
- [ ] Tasks should be dynamically added via JavaScript. Kindly, create a new JS file then add an array containing at least three `objects` holding tasks.
- [ ] After creating the required file above, please create a function that iterates over the tasks array and populates the HTML list item element for each task.
- [ ] On page load, the task array is rendered dynamically to the DOM. The tasks should appear in order of the `index` values for each task. I'd suggest using the `window.onLoad` function.

2022-03-24 11:45 UTC, omar-labana commented on README.md
> +
- [ ] Please fill or remove these sections to maintain constant format across the README file.

2022-03-24 16:03 UTC, FrederickMih requested changes
Hi @Theophileaseh , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 16:03 UTC, FrederickMih commented on src/modules/storage.js
> +export let listArray = [];
- [ ] I'm just so happy because of the effort you are putting forth to move ahead. You have added a function that iterates over this empty task array(l`istArray`), but nothing is being rendered on page load. You will need to initialize this listArray with some objects as pointed out by the previous reviewer. Each object should contain three keys - description [string], completed [bool], index [number].

2022-03-24 16:03 UTC, FrederickMih commented on README.md
> +# Project Name
- [optional ] Please kindly include the project name here instead of the text **Project Name**

2022-03-24 16:03 UTC, FrederickMih commented on README.md
> +### Deployment
- [ ] As pointed out by the previous code reviewer, let's make sure that our README file is descriptive and professional. You will need to fill or remove sections that are not necessary for this project. Walk through your README file once more and make sure that all sections are very descriptive.

2022-03-24 19:31 UTC, GzimAsani requested changes
# Hi @Theophileaseh , 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors. Kindly fix them

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-03-25 05:15 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @Theophileaseh , 

Great work on making the changes requested by the previous reviewer 👏 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 05:50 UTC, merged